"""empty message

Revision ID: 12717b0032c3
Revises: 6cb2b8315856
Create Date: 2020-05-21 17:23:24.003996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12717b0032c3'
down_revision = '6cb2b8315856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('datatimeevent_ibfk_1', 'datatimeevent', type_='foreignkey')
    op.create_foreign_key(None, 'datatimeevent', 'patients', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_constraint('labevents_ibfk_1', 'labevents', type_='foreignkey')
    op.create_foreign_key(None, 'labevents', 'patients', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_constraint('prescription_ibfk_1', 'prescription', type_='foreignkey')
    op.create_foreign_key(None, 'prescription', 'patients', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescription', type_='foreignkey')
    op.create_foreign_key('prescription_ibfk_1', 'prescription', 'patients', ['subject_id'], ['subject_id'])
    op.drop_constraint(None, 'labevents', type_='foreignkey')
    op.create_foreign_key('labevents_ibfk_1', 'labevents', 'patients', ['subject_id'], ['subject_id'])
    op.drop_constraint(None, 'datatimeevent', type_='foreignkey')
    op.create_foreign_key('datatimeevent_ibfk_1', 'datatimeevent', 'patients', ['subject_id'], ['subject_id'])
    # ### end Alembic commands ###
