"""empty message

Revision ID: 49997241863f
Revises: 7866feca65af
Create Date: 2020-05-29 14:37:42.907807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49997241863f'
down_revision = '7866feca65af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pwd', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pwd')
    op.drop_column('users', 'permission')
    # ### end Alembic commands ###
